# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91ba1cb041c64a1a9b5443e1f228dce52298ef401e138cbcc6acc5399b14dfef137b54aaa938e34d6e3c0f1548eb1ec770db8e4ea43e728649a046bbe1551a0a

test:
  secret_key_base: 29123b38b20f9176f7d8d211b35c9acce5793b11281d13aff6d647eb81a48c50955e7ff437c1bd7262a47e7ec604b2aa506393affb726b6343212187385ebb50

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
